In [8]:
import numpy as np
arr = np.random.randint(0,25,4)
print(arr)

[13  2 21  9]


In [9]:
arr.argmin()

1

In [10]:
arr.argmax()

2

In [16]:
two_d = np.array([[10,20,30], [40,50,60], [60,70,80]])
two_d[:1, :2]

array([[10, 20]])

In [20]:
import pandas as pd
my_data = {"country":['India','US','UK'],"Value":[200,50,40]}
df = pd.DataFrame(my_data)
df


country  Value
0   India    200
1      US     50
2      UK     40

In [22]:
country = ['India', 'USA','Pakistan']
rank = [1,2,-1]
pd.Series(country, rank)

 1       India
 2         USA
-1    Pakistan
dtype: object

In [23]:
import numpy as np
np_array = np.random.randint(1,100, size=(6,6), dtype = np.int64)
print(np_array)

[[37 65 52 79 18 25]
 [62 91 50  5 44 29]
 [51 51 74 82  1 46]
 [52 94 61 83 24 82]
 [23 95 54 34 70  5]
 [34 80 33 31 28 98]]


In [25]:
x = [1,2,3,4,5]
y = [6,7,4,3,2]

In [26]:
np_x = np.array(x)
np_y = np.array(y)
print(type(np_x))
print(type(np_y))
print(len(np_y))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
5


In [27]:
np_z = np_x + np_y
print(np_z)
print(len(np_z))

[7 9 7 7 7]
5


In [28]:
#create an array of ones
np.ones((3,4),dtype = np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int64)

In [29]:
np_array_randm = np.random.random((2,2))
print(np_array_randm)

[[0.5741244  0.60493842]
 [0.92770208 0.55601723]]


In [30]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])